# Generated by Django 5.1.5 on 2025-02-02 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_book_is_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='is_available',
        ),
        migrations.AddField(
            model_name='book',
            name='book_category',
            field=models.CharField(choices=[('النحو', 'nahw'), ('الصرف', 'sorf')], default=None, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='book_format',
            field=models.CharField(choices=[('ورقية', 'hard'), ('إلكترونية', 'soft')], default=None, max_length=10),
            preserve_default=False,
        ),
    ]
